language: bash
services: docker
before_install:
  - cd rest-spring-boot-crud-persons/
  - echo "Estamos na Pata do docker!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push everborges/rest-spring-boot;
    docker push everborges/mysql-rest-spring-boot;
  on:
    branch: master
notifications:
  email: false
