version: '3.4'
services:
  db:
    image: everborges/mysql-rest-spring-boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot
    ports:
      - "3308:3306"
    networks:
      - udemy-networks
  rest-spring-boot:
    image: everborges/rest-spring-boot
    restart: always
    build: ./RestSpringBoot
    working_dir: /RestSpringBoot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestSpringBoot:/RestSpringBoot
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-networks
networks:
    udemy-networks:
        driver: bridge